### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by betogulliver** [ChenZhouUC/TorchStats#1]
Could you please specify the LICENSE for your code? thanks
MIT License, ...

**Comment by ChenZhouUC** [comment]
> Could you please specify the LICENSE for your code? thanks MIT License, ...

[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) 
Thanks! License added!

**Comment by betogulliver** [comment]
thank you!
